# Definimos una red interna para que los contenedores se comuniquen entre sí
networks:
  teamboard_net:
    driver: bridge

# Definimos volumenes para persistencia de datos
volumes:
  pg_data:
  portainer_data:
  
services:
  # Frontend
  frontend:
    build:
      context: ./frontend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${FRONTEND_PORT}
    networks:
      - teamboard_net
    depends_on:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: 256M

  # Backend
  backend:
    build:
      context: ./backend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${BACKEND_PORT}
    networks:
      - teamboard_net
    depends_on:
      database:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

  # Base de Datos
  database:
    image: postgres:16-alpine
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - teamboard_net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 256M

  # Panel Portainer
  portainer:
    image: "portainer/portainer-ce:2.40.0-alpine"
    restart: unless-stopped
    env_file: 
    - .env 
    ports: 
    - ${PORTAINER_PORT}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - teamboard_net
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: 128M
